name: pr-actions
on: [pull_request]

jobs:
  backend-jest-test:
    runs-on: ubuntu-latest
    container: satantime/puppeteer-node:16-bullseye-slim

    steps:
      - name: Check out repo code
        uses: actions/checkout@v2

      - name: Install deps
        run: yarn install --frozen-lockfile
        env:
          NODE_ENV: test
      - name: Lint
        run: yarn lint
      - name: test
        run: |
          yarn start-test &
          yarn jest
        env:
          NODE_ENV: test
